db.restaurantes.find()
db.restaurantes.find({},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurantes.find({},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurantes.find({},{_id:0, restaurant_id:1, name:1, borough:1, 'address.zipcode':1})
db.restaurantes.find({borough:"Bronx"}, {_id:0, restaurant_id:1, name:1, borough:1, 'address.zipcode':1})
db.restaurantes.find({borough:"Bronx"}, {_id:0, restaurant_id:1, name:1, borough:1, 'address.zipcode':1}, {limit:5})
db.restaurantes.find({borough:"Bronx"}, {_id:0, restaurant_id:1, name:1, borough:1, 'address.zipcode':1}, {skip:5, limit:5})
db.restaurantes.find({"grades.score":{$gt:90}}, {_id:0, restaurant_id:1, name:1, borough:1, "grades.score":1})
db.restaurantes.find({"grades.score":{$gt:80, $lt:100}}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, "grades.score": 1 })
db.restaurantes.find( {"address.coord.0":{$lt:-95.754168}}, { _id: 0, restaurant_id: 1, name: 1, "address.coord":1})
db.restaurantes.find( { $and: [ { cuisine: { $ne: "American " } },  { "grades.score": { $gt: 70 } }, { "address.coord.1": { $lt: -65.754168 } } ] }, { _id: 0, name: 1, cuisine: 1, "grades.score": 1, "address.coord":1 })
db.restaurantes.find( {   cuisine: { $ne: "American " } , "grades.score": { $gt: 70 } , "address.coord.0": { $lt: -65.54168 } }, { _id: 0, name: 1, cuisine: 1, "grades.score": 1, "address.coord":1 } )
db.restaurantes.find({ cuisine: {$ne: "American "}, "grades.grade": {$eq: "A"}, borough: {$ne: "Brooklyn"} }, { _id: 0, name: 1, cuisine: 1, "grades.grade": 1, borough:1 }).sort({ cuisine: -1 });
db.restaurantes.find({name:{$regex:/^Wil/}}, {_id:0,restaurante_id:1,name:1,cuisine:1,borough:1})
db.restaurantes.find({name:{$regex:/ces$/}}, {_id:0,restaurante_id:1,name:1,cuisine:1,borough:1})
db.restaurantes.find({name:{$regex:/Reg/}}, {_id:0,restaurante_id:1,name:1,cuisine:1,borough:1})
db.restaurantes.find({ $and: [{ borough: "Bronx" }, { $or: [{ cuisine: "American " }, { cuisine: "Chinese" }] }]}).projection({_id: 0, name: 1, borough: 1, cuisine: 1})